apiVersion: v1
kind: Service
metadata:
  name: deployment-nodeport-swe645
spec:
  type: NodePort
  selector:
    run: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nodeportobject
